name: Docker Image CI

on:
  push:
    branches: 
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag sptkl/recipes-app:$GITHUB_SHA
        docker tag sptkl/recipes-app:$GITHUB_SHA sptkl/recipes-app:latest 
    - name: Publish to Registry
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push sptkl/recipes-app:$GITHUB_SHA
        docker push sptkl/recipes-app:latest
